export const PROJECTS_DATA = [
  {
    id: '1',
    title: 'Mobile App Redesign',
    author: 'Alex Chen',
    priority: 'High',
    tasksCount: 34,
    membersCount: 6,
    dueDate: 'Dec 28',
    status: 'In Progress',
    progress: 68,
    themeColor: '#2563EB',
  },
  {
    id: '2',
    title: 'API Integration v3',
    author: 'Sarah Kim',
    priority: 'Critical',
    tasksCount: 18,
    membersCount: 4,
    dueDate: 'Jan 15',
    status: 'Todo',
    progress: 23,
    themeColor: '#8B5CF6',
  },
  {
    id: '3',
    title: 'Dashboard Analytics',
    author: 'Mike Ross',
    priority: 'Medium',
    tasksCount: 12,
    membersCount: 3,
    dueDate: 'Dec 10',
    status: 'Review',
    progress: 85,
    themeColor: '#10B981',
  },
  {
    id: '4',
    title: 'E-Commerce Platform',
    author: 'Emma Davis',
    priority: 'Low',
    tasksCount: 56,
    membersCount: 8,
    dueDate: 'Nov 30',
    status: 'Completed',
    progress: 100,
    themeColor: '#F59E0B',
  },
];

export const Mobile_AppDesign =[
   { id:"1",
    title:"Design system component Library",
    author:"Alex Chen",
    status:"In Progress",
   },
   { id:"2",
    title:"User authentication Flow",
    author:"Emma Devis",
    status:"Completed",
   },
   { id:"3",
    title:"Push Notification Service",
    author:"Alex Chen",
    status:"Backlog",
   },
   { id:"4",
    title:"Dark Mode Implementation",
    author:"Mike Ross",
    status:"Testing",
   },
   
]